### ISSUE TITLE
Antioch tests aren't getting disabled when Antioch is

### ISSUE THREAD

**Issue by roystgnr** [grinsfem/grins#410] opened 2016-05-31 03:37 UTC
So "make check" is getting a host of failures, not just skips

**Comment by roystgnr** [comment] 2016-05-31 03:41
We're also now incompatible with the newest Antioch master, thanks to my mistake - when Antioch is built with MetaPhysicL, it then depends on metaphysicl/compare_types.h, but we don't have any antioch_config function and so there's no way for us to automatically pass on the header directories for that dependency.  Not sure what the best fix is.

**Comment by pbauman** [comment] 2016-05-31 12:33
Thanks for reporting this. Obviously, I so rarely build without Antioch this crept in. I'll fix it this morning.

> We're also now incompatible with the newest Antioch master, thanks to my mistake - when Antioch is built with MetaPhysicL, it then depends on metaphysicl/compare_types.h, but we don't have any antioch_config function and so there's no way for us to automatically pass on the header directories for that dependency. Not sure what the best fix is.

My knee-jerk reaction is to update the antioch.m4 in libantioch to include the relevant headers if Antioch is using MetaPhyscL. That way, the user shouldn't need to do anything (other than updating their antioch.m4 installation) since MetaPhyscL is header-only.

**Comment by nicholasmalaya** [comment] 2016-05-31 12:54
Getting a build with/without antioch regression on the newly revived buildbot would help catch this in the future. @roystgnr I don't see any reason we could not host GRINS at our Texas buildbot, unless @pbauman disagreed. 

Just a thought.

**Comment by pbauman** [comment] 2016-05-31 12:55
I'd be thrilled to have you guys running this on your BuildBot server. I have my server, I'm just awaiting Civet being publicly released. @permcody any news on that?

**Comment by pbauman** [comment] 2016-05-31 14:18
Took care of this in 0dd005a in #408; thus it will be in the 0.7.0 release. Going ahead and closing this.

I've opened libantioch/antioch#205 to discuss the Antioch+MetaPhyscL issue.

**Closed by pbauman** 2016-05-31 14:18 UTC

**Comment by permcody** [comment] 2016-05-31 15:21
I'll check on it. I haven't asked anyone for the last two weeks. It's got to be imminent!
